// Code generated by "stringer -linecomment -type compareTypeOrderResult"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[minKeyDataType-1]
	_ = x[nullDataType-2]
	_ = x[nanDataType-3]
	_ = x[numbersDataType-4]
	_ = x[stringDataType-5]
	_ = x[documentDataType-6]
	_ = x[arrayDataType-7]
	_ = x[binDataType-8]
	_ = x[objectIDDataType-9]
	_ = x[booleanDataType-10]
	_ = x[dateDataType-11]
	_ = x[timestampDataType-12]
	_ = x[regexDataType-13]
	_ = x[maxKeyDataType-14]
}

const _compareTypeOrderResult_name = "minKeyDataTypenullDataTypenanDataTypenumbersDataTypestringDataTypedocumentDataTypearrayDataTypebinDataTypeobjectIDDataTypebooleanDataTypedateDataTypetimestampDataTyperegexDataTypemaxKeyDataType"

var _compareTypeOrderResult_index = [...]uint8{0, 14, 26, 37, 52, 66, 82, 95, 106, 122, 137, 149, 166, 179, 193}

func (i compareTypeOrderResult) String() string {
	i -= 1
	if i >= compareTypeOrderResult(len(_compareTypeOrderResult_index)-1) {
		return "compareTypeOrderResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _compareTypeOrderResult_name[_compareTypeOrderResult_index[i]:_compareTypeOrderResult_index[i+1]]
}
