// Code generated by "stringer -linecomment -type compareTypeOrderResult"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[minKeyDataType-1]
	_ = x[undefinedDataType-2]
	_ = x[nullDataType-3]
	_ = x[nanDataType-4]
	_ = x[numbersDataType-5]
	_ = x[stringDataType-6]
	_ = x[documentDataType-7]
	_ = x[arrayDataType-8]
	_ = x[binDataType-9]
	_ = x[objectIDDataType-10]
	_ = x[booleanDataType-11]
	_ = x[dateDataType-12]
	_ = x[timestampDataType-13]
	_ = x[regexDataType-14]
	_ = x[maxKeyDataType-15]
}

const _compareTypeOrderResult_name = "minKeyDataTypeundefinedDataTypenullDataTypenanDataTypenumbersDataTypestringDataTypedocumentDataTypearrayDataTypebinDataTypeobjectIDDataTypebooleanDataTypedateDataTypetimestampDataTyperegexDataTypemaxKeyDataType"

var _compareTypeOrderResult_index = [...]uint8{0, 14, 31, 43, 54, 69, 83, 99, 112, 123, 139, 154, 166, 183, 196, 210}

func (i compareTypeOrderResult) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_compareTypeOrderResult_index)-1 {
		return "compareTypeOrderResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _compareTypeOrderResult_name[_compareTypeOrderResult_index[idx]:_compareTypeOrderResult_index[idx+1]]
}
